import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Loader from "@/components/Loader";
import {
  collectionGroup,
  DocumentData,
  FirestoreDataConverter,
  getDocs,
  limit,
  query,
  where,
} from "firebase/firestore";
import { firestore } from "@/lib/firebase";
import { orderBy } from "lodash";
import { postToJSON } from "@/helpers/getUserWithUsername";
import { useState } from "react";
import PostFeed from "@/components/PostFeed";

const LIMIT = 1;
export async function getServerSideProps(context) {
  const ref: FirestoreDataConverter<DocumentData> | null = collectionGroup(
    firestore,
    "posts"
  );
  const postQuery = query<{
    collections: string[];
    limit: number;
    where?: boolean;
    orderBy?: string;
  }>(
    ref,
    where("published", "==", true),
    orderBy("createdAt", "desc"),
    limit(LIMIT)
  );
  const posts = (await getDocs(postQuery)).docs.map(postToJSON);
  return {
    props: { posts },
  };
}

export default function Home(props: any) {
  const [posts, setPosts] = useState(props.posts);
  const [loading, setLoading] = useState(false);
  const [postsEnd, setPostsEnd] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home Page</h1>
        <Link
          href={{
            pathname: "/enter",
            // query: { name: "Ibran" },
          }}
        >
          Enter
        </Link>
        <div>
          <Loader show />
        </div>
        <div>
          <PostFeed posts={posts} admin={false} />
          {!loading && !postsEnd && (
            <button onClick={getMorePost}>Load More</button>
          )}
          <Loader show={loading} />
          {postsEnd && "You have reached the end!"}
        </div>
      </main>
    </>
  );
}
