import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Loader from "@/components/Loader";
import {
  collection,
  collectionGroup,
  DocumentData,
  FirestoreDataConverter,
  getDocs,
  limit,
  query,
  startAfter,
  Timestamp,
  where,
  orderBy,
} from "firebase/firestore";
import { firestore } from "@/lib/firebase";
import { postToJSON } from "@/helpers/getUserWithUsername";
import { useState } from "react";
import PostFeed from "@/components/PostFeed";

const LIMIT = 1;
export async function getServerSideProps() {
  const ref = collectionGroup(firestore, "posts");
  const postsQuery = query(
    ref,
    where("published", "==", true),
    orderBy("createdAt", "desc"),
    limit(LIMIT)
  );

  // const posts = (await getDocs(postsQuery)).docs.map(postToJSON);
  const docResult = await getDocs(postsQuery);
  let posts = docResult.docs.map(postToJSON);
  return {
    props: { posts }, // will be passed to the page component as props
  };
}

export default function Home(props: any) {
  const [posts, setPosts] = useState(props.posts);
  const [loading, setLoading] = useState(false);
  const [postsEnd, setPostsEnd] = useState(false);
  const getMorePosts = async () => {
    setLoading(true);
    const last = posts[posts.length - 1];
    const cursor =
      typeof last.createdAt === "number"
        ? Timestamp.fromMillis(last.createdAt)
        : last.createdAt;
    const nextQuery = query(
      collectionGroup(firestore, "posts"),
      where("published", "==", true),
      orderBy("createdAt", "desc"),
      startAfter(cursor),
      limit(1)
    );
    const newPosts = (await getDocs(nextQuery)).docs.map((doc) => doc.data());
    console.log("new posts: ", newPosts);
    setPosts(posts.concat(newPosts));
    setLoading(false);
    if (newPosts.length == 0) {
      setPostsEnd(true);
      // setLoading(false);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home Page</h1>
        <Link
          href={{
            pathname: "/enter",
            // query: { name: "Ibran" },
          }}
        >
          Enter
        </Link>
        {/* <div>
          <Loader show />
        </div> */}
        <div>
          <PostFeed posts={posts} admin={false} />
          {!loading && !postsEnd && (
            <button onClick={getMorePosts}>Load More</button>
          )}
          <Loader show={loading} />
          {postsEnd && "You have reached the end!"}
        </div>
      </main>
    </>
  );
}
